#
# Local setup
#
version: '3'

services:
  nginx:
    container_name: laravel_docker_nginx
    image: nginx:latest
    ports:
    - "8090:80"
    - "443:443"
    volumes:
    - ./:/var/www
    - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    links:
    - app
    networks:
      the_net:
        aliases:
        - 'laravel-docker'

  app:
    container_name: app
    build:
      context: ./
      dockerfile: docker/app.docker
    environment:
      VIRTUAL_HOST: laravelDocker
      DB_HOST: database
      DB_PORT: 5432
      PHP_IDE_CONFIG: serverName=laravelDocker
    volumes:
    - ./:/var/www
    networks:
    - the_net
    links:
    - database

  database:
    container_name: laravel_docker_db
    image: postgres:10
    environment:
      POSTGRES_DB: obot_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - "5433:5432"
    volumes:
    - laravel_docker_db_data:/var/lib/postgresql/data
    networks:
    - the_net

volumes:
  laravel_docker_db_data:

networks:
  the_net:
    driver: "bridge"
